# 不需要多语言的参数配置
favicon: "/radondb.ico"
# 首页第三行黑色背景的tag
radondb_projects:
  - MySQL
  - PostgreSQL
  - Redis
  - MongoDB
  - ClickHouse
  - ElesticSearch
  - OpenSearch

# 全局弹窗，如需要翻译，请移动下面的参数到 languages.yaml 中的params下面，其他的不需要改
